name: forte2

channels:
  - conda-forge
  - nodefaults

dependencies:
    - python=3.12
    - pip
    - nanobind>=1.3.2
    - cxx-compiler
    - libopenblas=*=*openmp*
    - libblas=*=*openblas
    - cmake=3.26
    - numpy
    - scipy
    - eigen
    - boost
    - scikit-build-core>=0.10
    - pytest
    - pytest-cov
    - conda-forge::libint
    - conda-forge::regex
    - conda-forge::basis_set_exchange
